### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception

### ISSUE THREAD

**Issue by sourya-sen** [thomasgeissl/ofPackageManager#24] opened 2019-10-18 07:57 UTC
Just did a fresh install, followed steps to install locally. On trying to install my first package with package manager, getting this.

```
Souryas-MacBook-Pro:ofPath_Test ayruos$ ofPackageManager install ofxMidi
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null
Abort trap: 6
```

**Comment by thomasgeissl** [comment] 2019-10-18 08:06
Hey Sourya, tahnks for testing.
I cannot reproduce it, but Davide reported a similar issue.
Does the error also occur if you run `ofPackageManager install danomatika/ofxMidi`? 

Where did you install the database? I think i have only tested with the default path.

**Comment by sourya-sen** [comment] 2019-10-18 08:39
Here's the info output

```
[ notice ] ofPackageManager: info
[ notice ] version: 0.0.13
[ notice ] path: TODO
[ notice ] global config path: /Users/ayruos/.ofPackageManager.json
[ notice ] Thanks for using ofPackageManager. If you find a bug then please report it on the github issue tracker (https://github.com/thomasgeissl/ofPackageManager/issues). See you soon.
```

Same error w/ full `ofPackageManager install danomatika/ofxMidi`

```
Souryas-MacBook-Pro:ofPath_Test ayruos$ ofPackageManager install danomatika/ofxMidi
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null
Abort trap: 6
```

I'm using a Nightly (of_v20191008_osx_release) w/ Xcode 11.1 - could this have something to do with this? And/or I've not set it up properly?

**Comment by thomasgeissl** [comment] 2019-10-18 08:42
did you install it via brew or compile it?

**Comment by thomasgeissl** [comment] 2019-10-18 08:45
whats the content of /Users/ayruos/.ofPackageManager.json
is there a local config in your directory?

**Comment by edap** [comment] 2019-10-18 08:52
Let's use this thread for report, Souryas, we are on the same error.

**Comment by edap** [comment] 2019-10-18 08:54
In my case, the exception happens because the file `.ofPackageManager.json` does not exists in my folder.

**Comment by thomasgeissl** [comment] 2019-10-18 08:56
It should check if it exits locally in your directory, if it does not then it checks the global config.

**Comment by sourya-sen** [comment] 2019-10-18 08:56
I have installed ofPackagaManager without the -g flag (only local). 
`/Users/ayruos/.ofPackageManager.json` does not exist.

But, the file does exist inside my oF directory.

```
Souryas-MacBook-Pro:of_v20191008_osx_release ayruos$ ls
CHANGELOG.md		LICENSE.md		apps			ofPackageManager.json
CODE_OF_CONDUCT.md	README.md		docs			other
INSTALL.md		THANKS.md		examples		projectGenerator
INSTALL_FROM_GITHUB.md	addons			libs			scripts
Souryas-MacBook-Pro:of_v20191008_osx_release ayruos$ cat ofPackageManager.json 
{
    "localAddonsPath": "local_addons",
    "ofPath": "/Users/ayruos/Develop/of_v20191008_osx_release",
    "packagesPath": "/Users/ayruos/.ofPackages"
}Souryas-MacBook-Pro:of_v20191008_osx_release ayruos$ 
```

(Installed via brew)

**Comment by thomasgeissl** [comment] 2019-10-18 08:58
For now it must be inside your project directory. But that is hardly tested.
There is the plan to recursly check the parent directories until root or there is a config available.

**Comment by sourya-sen** [comment] 2019-10-18 09:00
Right, gotcha. Running `ofPackageManager config` from inside the project folder removed the error and is installing addons. (Better documentation needed?)

**Comment by thomasgeissl** [comment] 2019-10-18 09:02
better documentation is needed, but i like the idea that it recursively checks the parents directory. so you can have a config per oF installation instead of only one global one.

**Comment by sourya-sen** [comment] 2019-10-18 09:03
Yeah, that would be super, I'm sure all of us have multiple oF versions installed, for various reasons.

**Comment by thomasgeissl** [comment] 2019-10-18 09:14
i will add this whenever i find some time.

**Comment by edap** [comment] 2019-10-18 09:15
Installing it gloabally solved the issue for me

**Comment by thomasgeissl** [comment] 2019-12-19 14:45
it should be fixed in the latest version. let me know if there are still problems.

**Closed by thomasgeissl** 2019-12-19 14:45 UTC
